[metadata]
name = cool-cool-latex-editor
version = 0.4.0
description = A lightweight, local, Git-native LaTeX review editor.
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
include_package_data = True
python_requires = >=3.9

[options.package_data]
cool_cool_latex_editor =
    static/*

[options.entry_points]
console_scripts =
    cool-cool-latex-editor = cool_cool_latex_editor.__main__:main
